create table customers (
    id bigint generated by default as identity,
    last_name varchar(255),
    name varchar(255),
    primary key (id)
);

create table items (
    id bigint generated by default as identity,
    amount double not null,
    name varchar(255),
    order_id bigint,
    primary key (id)
);

create table orders (
    id bigint generated by default as identity,
    date timestamp,
    total_amount double not null,
    customer_id bigint,
    primary key (id)
);

create table payments (
    id bigint generated by default as identity,
    amount double not null,
    date timestamp,
    order_id bigint,
    primary key (id)
);

alter table items add constraint FKirjef006njdi706iiqdfkgk9d foreign key (order_id) references orders;
alter table orders add constraint FKpxtb8awmi0dk6smoh2vp1litg foreign key (customer_id) references customers;
alter table payments add constraint FK81gagumt0r8y3rmudcgpbk42l foreign key (order_id) references orders;
